package Vista;
import Clases.*;
import Controladores.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/* @author Daniel Sarmiento  */

public class GestionReserva extends javax.swing.JFrame {
    ControladorAgente ControladorAgente;  //Declare
    ControladorVuelo ControladorVuelo;
    ControladorCliente ControladorCliente;
    ControladorAerolinea ControladorAerolinea;
    ControladorReportes ControladorReportes;
    ControladorExcel ControladorExcel;
    
    public GestionReserva() {
        initComponents();
        //Controller Part
        ControladorAgente = new ControladorAgente();
        ControladorVuelo = new ControladorVuelo();
        ControladorCliente = new ControladorCliente();
        ControladorAerolinea = new ControladorAerolinea();
        ControladorReportes = new ControladorReportes();
        ControladorExcel = new ControladorExcel();
        //UX  best User experience
        this.setTitle("Gestionador Aerolinea");
        this.setFocusable(true);
        this.setForeground(Color.red);
        this.setLocationRelativeTo(this);
        PnlGrrafico.setBackground(Color.red);
        CreadorAerolineaPd();
        RefrescarListaAgente();
        RefrescarListaVuelo();
        RefrescarOpcionesVuelo();
        RefrescarListaClinte();
    }
    
    public void CreadorAerolineaPd() {
        String Nombre = TxtNombreAerolinea.getText();
        String Ciudad = TxtCiudadadAerolinea.getText();
        int Nit = Integer.parseInt(TxtNitAerolinea.getText());   
        if (ControladorAerolinea.CntCreadorAerolinea(Nombre, Ciudad, Nit) ) {
            JOptionPane.showMessageDialog(rootPane,"Se creo un Aerolinea "+"\nCOn lainformacion de el modulo Aerolinea ");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        PnlGrrafico = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TxtNombreAerolinea = new javax.swing.JTextPane();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TxtCiudadadAerolinea = new javax.swing.JTextPane();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TxtNitAerolinea = new javax.swing.JTextPane();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        LstAgentesAerolinea = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        LstVuelosAerolinea = new javax.swing.JList<>();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LstVuelos = new javax.swing.JList<>();
        BtnCrearVuelo = new javax.swing.JButton();
        BtnBuscarVuelo = new javax.swing.JButton();
        BtnEliminarVuelo = new javax.swing.JButton();
        BtnActualizarAgente1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        TxtHoraLlegadaVuelo = new javax.swing.JTextField();
        TxtHoraSalidaVuelo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CmbTipoVuelo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        TxtOrigenVuelo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TxtDestinoVuelo = new javax.swing.JTextField();
        TxtCodigoVuelo = new javax.swing.JTextField();
        BtnVueloExcel = new javax.swing.JButton();
        PnlGraficos = new javax.swing.JPanel();
        BtnTipoPersonas = new javax.swing.JButton();
        BtnTipoVuelo = new javax.swing.JButton();
        BtnClienteGrafica = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TxtNombreAgente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtCedulaAgente = new javax.swing.JTextField();
        TxtCodigoAgente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtTelefonoAgente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxtCargoAgente = new javax.swing.JTextField();
        BtnCrearAgente = new javax.swing.JButton();
        BtnActualizarAgente = new javax.swing.JButton();
        BtnBuscarAgente = new javax.swing.JButton();
        BtnEliminarAgente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LstAgentes = new javax.swing.JList<>();
        BtnAgenteExcel = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        CmbVueloClientes = new javax.swing.JComboBox<>();
        BtnEliminarCliente = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        BtnCrearCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        LstClientes = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        CmbTipoClientes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TxtPasaporteCliente = new javax.swing.JTextField();
        TxtCorreoECliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtNombreCliente = new javax.swing.JTextField();
        TxtDireccionCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtTelefonoCliente = new javax.swing.JTextField();
        TxtCedulaCliente = new javax.swing.JTextField();
        BtnBuscarCliente = new javax.swing.JButton();
        BtnClienteExcel = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlGrrafico.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PnlGrraficoPropertyChange(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Nombre");

        TxtNombreAerolinea.setText("Ravianca");
        TxtNombreAerolinea.setToolTipText("");
        jScrollPane4.setViewportView(TxtNombreAerolinea);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Ciudad");

        TxtCiudadadAerolinea.setText("Santa FE");
        TxtCiudadadAerolinea.setToolTipText("");
        jScrollPane5.setViewportView(TxtCiudadadAerolinea);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Nit");

        TxtNitAerolinea.setText("123456");
        jScrollPane6.setViewportView(TxtNitAerolinea);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Agentes");

        jScrollPane7.setViewportView(LstAgentesAerolinea);

        jScrollPane8.setViewportView(LstVuelosAerolinea);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Vuelos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane5)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        PnlGrrafico.addTab("Administrador Aerolinea", jPanel1);

        jScrollPane2.setViewportView(LstVuelos);

        BtnCrearVuelo.setText("Crear");
        BtnCrearVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearVueloActionPerformed(evt);
            }
        });

        BtnBuscarVuelo.setText("Buscar");
        BtnBuscarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarVueloActionPerformed(evt);
            }
        });

        BtnEliminarVuelo.setText("Eliminar");
        BtnEliminarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarVueloActionPerformed(evt);
            }
        });

        BtnActualizarAgente1.setText("Actualizar");
        BtnActualizarAgente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarAgente1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Hora Llegada");

        TxtHoraLlegadaVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHoraLlegadaVueloActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Hora salida");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Tipo");

        CmbTipoVuelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Internacional" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Origen");

        TxtOrigenVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOrigenVueloActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Destino");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Codigo");

        TxtCodigoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoVueloActionPerformed(evt);
            }
        });

        BtnVueloExcel.setText("Reporte");
        BtnVueloExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVueloExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                                    .addComponent(BtnCrearVuelo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TxtOrigenVuelo)
                                            .addComponent(CmbTipoVuelo, 0, 172, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(BtnBuscarVuelo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BtnEliminarVuelo))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(TxtHoraSalidaVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(69, 69, 69)
                                        .addComponent(BtnActualizarAgente1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtDestinoVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(TxtCodigoVuelo)
                                    .addComponent(TxtHoraLlegadaVuelo)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(BtnVueloExcel)
                                        .addGap(74, 74, 74))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtOrigenVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDestinoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbTipoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtHoraSalidaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtHoraLlegadaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCrearVuelo)
                    .addComponent(BtnBuscarVuelo)
                    .addComponent(BtnEliminarVuelo)
                    .addComponent(BtnActualizarAgente1)
                    .addComponent(BtnVueloExcel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        PnlGrrafico.addTab("Administrador Vuelo", jPanel3);

        BtnTipoPersonas.setText("Personas");
        BtnTipoPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTipoPersonasActionPerformed(evt);
            }
        });

        BtnTipoVuelo.setText("Vuelo");
        BtnTipoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTipoVueloActionPerformed(evt);
            }
        });

        BtnClienteGrafica.setText("Clientes");
        BtnClienteGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClienteGraficaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlGraficosLayout = new javax.swing.GroupLayout(PnlGraficos);
        PnlGraficos.setLayout(PnlGraficosLayout);
        PnlGraficosLayout.setHorizontalGroup(
            PnlGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlGraficosLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(BtnTipoPersonas)
                .addGap(121, 121, 121)
                .addComponent(BtnTipoVuelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(BtnClienteGrafica)
                .addGap(89, 89, 89))
        );
        PnlGraficosLayout.setVerticalGroup(
            PnlGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlGraficosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PnlGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTipoPersonas)
                    .addComponent(BtnTipoVuelo)
                    .addComponent(BtnClienteGrafica))
                .addContainerGap(353, Short.MAX_VALUE))
        );

        PnlGrrafico.addTab("Graficas", PnlGraficos);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nombre");

        TxtNombreAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreAgenteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cedula");

        TxtCodigoAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoAgenteActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Codigo");

        TxtTelefonoAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonoAgenteActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Telefono");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cargo");

        BtnCrearAgente.setText("Crear");
        BtnCrearAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearAgenteActionPerformed(evt);
            }
        });

        BtnActualizarAgente.setText("Actualizar");
        BtnActualizarAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarAgenteActionPerformed(evt);
            }
        });

        BtnBuscarAgente.setText("Buscar");
        BtnBuscarAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarAgenteActionPerformed(evt);
            }
        });

        BtnEliminarAgente.setText("Eliminar");
        BtnEliminarAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarAgenteActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(LstAgentes);

        BtnAgenteExcel.setText("Reportes");
        BtnAgenteExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgenteExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtNombreAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TxtTelefonoAgente, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(TxtCargoAgente))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(BtnCrearAgente)
                                .addGap(55, 55, 55)
                                .addComponent(BtnActualizarAgente)
                                .addGap(46, 46, 46)
                                .addComponent(BtnBuscarAgente)
                                .addGap(36, 36, 36)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BtnEliminarAgente)
                                .addGap(42, 42, 42)
                                .addComponent(BtnAgenteExcel))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtCedulaAgente, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                .addComponent(TxtCodigoAgente)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNombreAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCedulaAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTelefonoAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCodigoAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCargoAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnActualizarAgente)
                    .addComponent(BtnBuscarAgente)
                    .addComponent(BtnEliminarAgente)
                    .addComponent(BtnCrearAgente)
                    .addComponent(BtnAgenteExcel))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        PnlGrrafico.addTab("Administrdor Agente", jPanel2);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Vuelo");

        CmbVueloClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbVueloClientesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CmbVueloClientesMousePressed(evt);
            }
        });
        CmbVueloClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbVueloClientesActionPerformed(evt);
            }
        });

        BtnEliminarCliente.setText("Eliminar");
        BtnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarClienteActionPerformed(evt);
            }
        });

        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        BtnCrearCliente.setText("Crear");
        BtnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearClienteActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(LstClientes);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tipo");

        CmbTipoClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<None>", "Premium", "Vip" }));
        CmbTipoClientes.setAutoscrolls(true);
        CmbTipoClientes.setFocusCycleRoot(true);
        CmbTipoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbTipoClientesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Correo Electronico");

        TxtPasaporteCliente.setText(" ");

        TxtCorreoECliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCorreoEClienteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Numero de pasaporte");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dirección");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre");

        TxtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreClienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cedula");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Telefono");

        TxtTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonoClienteActionPerformed(evt);
            }
        });

        BtnBuscarCliente.setText("Buscar");
        BtnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarClienteActionPerformed(evt);
            }
        });

        BtnClienteExcel.setText("Reporte");
        BtnClienteExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClienteExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CmbTipoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(TxtPasaporteCliente)))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(CmbVueloClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(TxtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                            .addGap(43, 43, 43)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(TxtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(TxtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(TxtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(BtnCrearCliente)
                                            .addGap(50, 50, 50)
                                            .addComponent(BtnBuscarCliente)))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(TxtCorreoECliente))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(69, 69, 69)
                                            .addComponent(BtnActualizar)
                                            .addGap(58, 58, 58)
                                            .addComponent(BtnEliminarCliente)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BtnClienteExcel)
                                            .addGap(32, 32, 32)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCorreoECliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPasaporteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CmbTipoClientes))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbVueloClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCrearCliente)
                    .addComponent(BtnActualizar)
                    .addComponent(BtnEliminarCliente)
                    .addComponent(BtnBuscarCliente)
                    .addComponent(BtnClienteExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PnlGrrafico.addTab("Administracion Cliente", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PnlGrrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(PnlGrrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreAgenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreAgenteActionPerformed

    private void TxtCodigoAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoAgenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoAgenteActionPerformed

    private void TxtTelefonoAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonoAgenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefonoAgenteActionPerformed

    private void BtnCrearAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearAgenteActionPerformed
        String Nombre = TxtNombreAgente.getText();   //Take impormation for User
        int Cedula = Integer.parseInt(TxtCedulaAgente.getText()); //Beware for future this date type would be short, i recomender long
        long NumTelefono = Long.parseLong(TxtTelefonoAgente.getText());// use inthis case because for international number 44 7817688549
        int Codigo = Integer.parseInt(TxtCodigoAgente.getText());
        String Cargo = TxtCargoAgente.getText();
        if (ControladorAgente.CntCrearAgente(Codigo, Cargo, Cedula, Nombre, NumTelefono)) {
            
            JOptionPane.showMessageDialog(this, "Agente " + Nombre + " creado exitosamente.");
            RefrescarListaAgente();
            LimpiarDatosAgente();
        }
        else JOptionPane.showMessageDialog(this, "Nose pudo realizar el registro.");;
        
    }//GEN-LAST:event_BtnCrearAgenteActionPerformed

    private void BtnActualizarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarAgenteActionPerformed
        int Cedula = Integer.parseInt(TxtCedulaAgente.getText());// Get Ingormation
        boolean Encontrar = ControladorAgente.CntBuscarAgente(Cedula);
        if (Encontrar) {
            String Nombre = TxtNombreAgente.getText();   //Take impormation for User
            long NumTelefono = Long.parseLong(TxtTelefonoAgente.getText());// use inthis case because for international number 44 7817688549
            int Codigo = Integer.parseInt(TxtCodigoAgente.getText());
            String Cargo = TxtCargoAgente.getText();
            if (ControladorAgente.CntActualizarAgente(Codigo, Cargo, Cedula, Nombre, NumTelefono)) {
                RefrescarListaAgente();
                System.out.println("lologro");
                JOptionPane.showMessageDialog(this, "Agente Actualizado Exitosamente.");
            }

        }else JOptionPane.showMessageDialog(this,"Error, Codgio no encontrado.");
    }//GEN-LAST:event_BtnActualizarAgenteActionPerformed

    private void BtnBuscarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarAgenteActionPerformed
        int Cedula = Integer.parseInt(TxtCedulaAgente.getText());// Get Ingormation
        if (ControladorAgente.CntBuscarAgente(Cedula)) {
            Agente Agente = ControladorAgente.CntTraerAgente(Cedula);
            TxtNombreAgente.setText(Agente.getNombre());
            TxtCargoAgente.setText(Agente.getCargo());
            TxtCodigoAgente.setText(Agente.getCodigo()+"");
            TxtTelefonoAgente.setText(Agente.getNumCelular() + "");
            JOptionPane.showMessageDialog(this,"Sujeto Encontrado.");
        }else JOptionPane.showMessageDialog(this,"Error, Revise los Datos.");
    }//GEN-LAST:event_BtnBuscarAgenteActionPerformed

    private void BtnEliminarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarAgenteActionPerformed
        int Cedula = Integer.parseInt(TxtCedulaAgente.getText());// Get Ingormation
        if (ControladorAgente.CntBuscarAgente(Cedula)) {
            int Opcion = JOptionPane.showConfirmDialog(this, "Seguro desea Eliminarlo");
            if (Opcion == 0){
                if (ControladorAgente.CntEliminarAgente(Cedula)) JOptionPane.showMessageDialog(this, "Agente eliminado exitosamente");
                RefrescarListaAgente();
            }
        }else JOptionPane.showMessageDialog(this,"Error, Codigo no encontrado.");
    }//GEN-LAST:event_BtnEliminarAgenteActionPerformed

    private void BtnCrearVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearVueloActionPerformed
        String Codigo = TxtCodigoVuelo.getText();
        String Origen = TxtOrigenVuelo.getText();
        String HoraSalida = TxtHoraSalidaVuelo.getText();
        String Destino = TxtDestinoVuelo.getText();
        String HoraLlegada = TxtHoraLlegadaVuelo.getText();
        String Tipo = CmbTipoVuelo.getSelectedItem().toString();
        if (ControladorVuelo.CntCrearVuelo(Codigo, Origen, HoraSalida, Destino, HoraLlegada, Tipo)){            
            RefrescarOpcionesVuelo();
            RefrescarListaVuelo();
            JOptionPane.showMessageDialog(this, "Vuelo " + Codigo," creado exitosamente.", HEIGHT);
        }
        else JOptionPane.showMessageDialog(rootPane,"Error revisar los datos.");
    }//GEN-LAST:event_BtnCrearVueloActionPerformed

    private void BtnBuscarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarVueloActionPerformed
        String Codigo = TxtCodigoVuelo.getText();
        if ( ControladorVuelo.CntBuscarVuelo(Codigo) ) {
            Vuelo Vuelo = ControladorVuelo.CntTraerVuelo(Codigo); //get Flight and put atribute in Textfields
            TxtCodigoVuelo.setText(Vuelo.getCodigo());
            TxtOrigenVuelo.setText(Vuelo.getOrigen());
            TxtDestinoVuelo.setText(Vuelo.getDestino());
            TxtHoraSalidaVuelo.setText(Vuelo.getHoraSalida());
            TxtHoraLlegadaVuelo.setText(Vuelo.getHoraLlegada());
            CmbTipoVuelo.setSelectedItem(Vuelo.getTipo());
            JOptionPane.showMessageDialog(this, "Vuelo encotrado");
        }else JOptionPane.showMessageDialog(this, "Vuelo no encontrado, intente nuevamente.");
    }//GEN-LAST:event_BtnBuscarVueloActionPerformed

    private void BtnEliminarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarVueloActionPerformed
        String Codigo = TxtCodigoVuelo.getText();
        boolean EncontrarVuelo = ControladorVuelo.CntBuscarVuelo(Codigo);
        if (EncontrarVuelo) {
            if (ControladorVuelo.CntEliminarVuelo(Codigo)) {
                JOptionPane.showMessageDialog(this, "Eliminado correctamente");
                RefrescarListaVuelo();
            }
 
        }else JOptionPane.showMessageDialog(this, "Vuelo no encontrado, intente nuevamente.");

    }//GEN-LAST:event_BtnEliminarVueloActionPerformed

    private void BtnActualizarAgente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarAgente1ActionPerformed
        String Codigo = TxtCodigoVuelo.getText();
        if (ControladorVuelo.CntBuscarVuelo(Codigo)) {
            String Origen = TxtOrigenVuelo.getText();
            String HoraSalida = TxtHoraSalidaVuelo.getText();
            String Destino = TxtDestinoVuelo.getText();
            String HoraLlegada = TxtHoraLlegadaVuelo.getText();
            String Tipo = CmbTipoVuelo.getSelectedItem().toString();
            if (ControladorVuelo.CntActualizarVuelo(Codigo, Origen, HoraSalida, Destino, HoraLlegada, Tipo)) {
                JOptionPane.showMessageDialog(this, "Actualizado correctamente");
                RefrescarListaVuelo();
            }
        }else JOptionPane.showMessageDialog(this, "Vuelo no encontrado, intente nuevamente.");
    }//GEN-LAST:event_BtnActualizarAgente1ActionPerformed

    private void TxtHoraLlegadaVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHoraLlegadaVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHoraLlegadaVueloActionPerformed

    private void TxtOrigenVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOrigenVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOrigenVueloActionPerformed

    private void TxtCodigoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoVueloActionPerformed

    private void CmbVueloClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbVueloClientesMouseClicked

    }//GEN-LAST:event_CmbVueloClientesMouseClicked

    private void CmbVueloClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbVueloClientesMousePressed

    }//GEN-LAST:event_CmbVueloClientesMousePressed

    private void CmbVueloClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbVueloClientesActionPerformed

    }//GEN-LAST:event_CmbVueloClientesActionPerformed

    private void BtnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarClienteActionPerformed
        int Cedula = Integer.parseInt(TxtCedulaCliente.getText());
        if (ControladorCliente.CntBucarCliente(Cedula)) {
            int Opcion = JOptionPane.showConfirmDialog(this, "Seguro desea Eliminarlo");
            if (Opcion == 0){
                if (ControladorCliente.CntEliminarCliente(Cedula)) {
                    JOptionPane.showMessageDialog(this, "Cliente eliminado exitosamente");
                    LimpiarDatosCliente();
                    RefrescarListaClinte();
                }
            }
        }else JOptionPane.showMessageDialog(this,"Error, Codigo no encontrado.");
        // boolean Resultado = ControladorAgente.CntBuscarAgente(Codigo);
    }//GEN-LAST:event_BtnEliminarClienteActionPerformed

    private void BtnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearClienteActionPerformed
        String Nombre = TxtNombreCliente.getText();
        int Cedula = Integer.parseInt(TxtCedulaCliente.getText());
        long NumTelefono = Long.parseLong(TxtTelefonoCliente.getText());
        String Email = TxtCorreoECliente.getText();
        String Direccion = TxtDireccionCliente.getText();
        String Pasaporte = TxtPasaporteCliente.getText();
        String Tipo = CmbTipoClientes.getSelectedItem().toString();
        String Seleccion = CmbVueloClientes.getSelectedItem().toString();      
        Vuelo Vuelo = ControladorVuelo.CntTraerVueloSeleccionado(Seleccion);
        Cliente Cliente = new Cliente(Direccion, Email, Pasaporte, Tipo, Vuelo, null, Cedula, Nombre, NumTelefono);
        if (ControladorCliente.CntCrearCliente(Cliente)) {
            JOptionPane.showMessageDialog(this,"Creado exitosamente");
            RefrescarListaClinte();
            LimpiarDatosCliente();
        } else {JOptionPane.showMessageDialog(this,"No creado");
        }
    }//GEN-LAST:event_BtnCrearClienteActionPerformed

    private void TxtCorreoEClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCorreoEClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCorreoEClienteActionPerformed

    private void TxtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreClienteActionPerformed

    private void TxtTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefonoClienteActionPerformed

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        String Nombre = TxtNombreCliente.getText();
        int Cedula = Integer.parseInt(TxtCedulaCliente.getText());
        long NumTelefono = Long.parseLong(TxtTelefonoCliente.getText());
        String Email = TxtCorreoECliente.getText();
        String Direccion = TxtDireccionCliente.getText();
        String Pasaporte = TxtPasaporteCliente.getText();
        String Tipo = CmbTipoClientes.getSelectedItem().toString();
        String Seleccion = CmbVueloClientes.getSelectedItem().toString();      
        Vuelo Vuelo = ControladorVuelo.CntTraerVueloSeleccionado(Seleccion);
        Cliente Cliente = new Cliente(Direccion, Email, Pasaporte, Tipo, Vuelo, null, Cedula, Nombre, NumTelefono);
        if (ControladorCliente.CntBucarCliente(Cedula)) {            
            JOptionPane.showMessageDialog(this, "Actualizado correctamente.");
        } else {JOptionPane.showMessageDialog(this,"NoEncontrado");
        }
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarClienteActionPerformed
        int Cedula = Integer.parseInt(TxtCedulaCliente.getText());
        if (ControladorCliente.CntBucarCliente(Cedula)) {
            Cliente Cliente = ControladorCliente.CntTraerCliente(Cedula);
            TxtNombreCliente.setText(Cliente.getNombre());
            TxtDireccionCliente.setText(Cliente.getDreccion());
            TxtCorreoECliente.setText(Cliente.getEmail());
            CmbTipoClientes.setSelectedItem(Cliente.getTipo());
            TxtTelefonoCliente.setText(Cliente.getNumCelular()+ "");
            TxtPasaporteCliente.setText(Cliente.getPasaporte());
            JOptionPane.showMessageDialog(this, "Encontrado");
        } else { JOptionPane.showMessageDialog(this, "No Encontrado");
        }
    }//GEN-LAST:event_BtnBuscarClienteActionPerformed

    private void BtnAgenteExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgenteExcelActionPerformed
        JFileChooser Propiedades = new JFileChooser();
        Propiedades.setDialogTitle("Nombre y ruta Archivo Agente");
        int Seleccion = Propiedades.showOpenDialog(jPanel1);
        if (Seleccion == JFileChooser.APPROVE_OPTION) {//if user told he wants
            File Archivo = Propiedades.getSelectedFile();
            String NombreArchivo = Archivo.getName();
            String Ruta = Propiedades.getSelectedFile().getAbsolutePath();
            if (ControladorExcel.CntAgenteExcel(NombreArchivo)) {
                JOptionPane.showMessageDialog(this, "ArchivoGenerado Exxitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Lo Sentimos el Archivo esta Abierto u Manipulado","Error",3);
            }
        }
        
    }//GEN-LAST:event_BtnAgenteExcelActionPerformed

    private void CmbTipoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbTipoClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbTipoClientesActionPerformed

    private void PnlGrraficoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PnlGrraficoPropertyChange

    }//GEN-LAST:event_PnlGrraficoPropertyChange

    private void BtnTipoPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTipoPersonasActionPerformed
        GraficosPer VentaEmergente = new GraficosPer();
        VentaEmergente.setVisible(true);
    }//GEN-LAST:event_BtnTipoPersonasActionPerformed

    private void BtnTipoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTipoVueloActionPerformed
        GraficosVuelo VentanaEmergente = new GraficosVuelo();
        VentanaEmergente.setVisible(true);
    }//GEN-LAST:event_BtnTipoVueloActionPerformed

    private void BtnClienteGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClienteGraficaActionPerformed
        GraficosClientes VentanaEmergente = new GraficosClientes();
        VentanaEmergente.setVisible(true);
    }//GEN-LAST:event_BtnClienteGraficaActionPerformed

    private void BtnVueloExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVueloExcelActionPerformed
        JFileChooser Propiedades = new JFileChooser();
        Propiedades.setDialogTitle("Nombre y ruta Archivo Agente");
        int Seleccion = Propiedades.showOpenDialog(jPanel1);
        if (Seleccion == JFileChooser.APPROVE_OPTION) {//if user told he wants
            File Archivo = Propiedades.getSelectedFile();
            String NombreArchivo = Archivo.getName();
            String Ruta = Propiedades.getSelectedFile().getAbsolutePath();
            if (ControladorExcel.CntVueloExcel(NombreArchivo)) {
                JOptionPane.showMessageDialog(this, "ArchivoGenerado Exxitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Lo Sentimos el Archivo esta Abierto u Manipulado","Error",3);
            }
        }
        
    }//GEN-LAST:event_BtnVueloExcelActionPerformed

    private void BtnClienteExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClienteExcelActionPerformed
        JFileChooser Propiedades = new JFileChooser();
        Propiedades.setDialogTitle("Nombre y ruta Archivo Agente");
        int Seleccion = Propiedades.showOpenDialog(jPanel1);
        if (Seleccion == JFileChooser.APPROVE_OPTION) {//if user told he wants
            File Archivo = Propiedades.getSelectedFile();
            String NombreArchivo = Archivo.getName();
            String Ruta = Propiedades.getSelectedFile().getAbsolutePath();
            if (ControladorExcel.CntClienteExcel(NombreArchivo)) {
                JOptionPane.showMessageDialog(this, "ArchivoGenerado Exxitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Lo Sentimos el Archivo esta Abierto u Manipulado","Error",3);
            }
        }
        
    }//GEN-LAST:event_BtnClienteExcelActionPerformed

    
    public void RefrescarListaVuelo() {
        DefaultListModel Model = ControladorVuelo.CntCrearListaModeloVuelo();
        LstVuelos.setModel(Model);
        LstVuelosAerolinea.setModel(Model);
    }
    
    //  methods downs it's beuty
    public void LimpiarDatosAgente() {
        TxtNombreAgente.setText("");
        TxtCargoAgente.setText("");
        TxtCodigoAgente.setText("");
        TxtCedulaAgente.setText("");
        TxtTelefonoAgente.setText("");
    }
    
    public void RefrescarListaAgente() {
       DefaultListModel Model = ControladorAgente.CntCrearListaModeloAgente();
       LstAgentes.setModel(Model);
       LstAgentesAerolinea.setModel(Model);
    }

    public void RefrescarListaClinte() {
       DefaultListModel Model = ControladorCliente.CntCrearListaModeloClientes();
       LstClientes.setModel(Model);
    }
    public void LimpiarDatosCliente() {
        TxtNombreCliente.setText("");
        TxtCorreoECliente.setText("");
        TxtDireccionCliente.setText("");
        TxtTelefonoCliente.setText("");
        TxtCedulaCliente.setText("");
        TxtPasaporteCliente.setText("");
        CmbTipoClientes.setSelectedIndex(0);
        
    }
    public void LimpiarDatosVuelos() {
        TxtCodigoVuelo.setText("");
        TxtOrigenVuelo.setText("");
        TxtDestinoVuelo.setText("");
        TxtHoraSalidaVuelo.setText("");
        TxtHoraLlegadaVuelo.setText("");
        CmbTipoVuelo.setSelectedItem(0);
    }       
    
    private void RefrescarOpcionesVuelo(){ // Refresh List for flights
        CmbVueloClientes.removeAllItems(); // CustomerViewer    
        List<String> InfoVuelos = ControladorVuelo.CntCrearListaStringModeloVuelo();
        int i = 0;
        for (String item : InfoVuelos) {
            CmbVueloClientes.insertItemAt(item, i);
            i++;
        } 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnActualizarAgente;
    private javax.swing.JButton BtnActualizarAgente1;
    private javax.swing.JButton BtnAgenteExcel;
    private javax.swing.JButton BtnBuscarAgente;
    private javax.swing.JButton BtnBuscarCliente;
    private javax.swing.JButton BtnBuscarVuelo;
    private javax.swing.JButton BtnClienteExcel;
    private javax.swing.JButton BtnClienteGrafica;
    private javax.swing.JButton BtnCrearAgente;
    private javax.swing.JButton BtnCrearCliente;
    private javax.swing.JButton BtnCrearVuelo;
    private javax.swing.JButton BtnEliminarAgente;
    private javax.swing.JButton BtnEliminarCliente;
    private javax.swing.JButton BtnEliminarVuelo;
    private javax.swing.JButton BtnTipoPersonas;
    private javax.swing.JButton BtnTipoVuelo;
    private javax.swing.JButton BtnVueloExcel;
    private javax.swing.JComboBox<String> CmbTipoClientes;
    private javax.swing.JComboBox<String> CmbTipoVuelo;
    private javax.swing.JComboBox<String> CmbVueloClientes;
    private javax.swing.JList<String> LstAgentes;
    private javax.swing.JList<String> LstAgentesAerolinea;
    private javax.swing.JList<String> LstClientes;
    private javax.swing.JList<String> LstVuelos;
    private javax.swing.JList<String> LstVuelosAerolinea;
    private javax.swing.JPanel PnlGraficos;
    private javax.swing.JTabbedPane PnlGrrafico;
    private javax.swing.JTextField TxtCargoAgente;
    private javax.swing.JTextField TxtCedulaAgente;
    private javax.swing.JTextField TxtCedulaCliente;
    private javax.swing.JTextPane TxtCiudadadAerolinea;
    private javax.swing.JTextField TxtCodigoAgente;
    private javax.swing.JTextField TxtCodigoVuelo;
    private javax.swing.JTextField TxtCorreoECliente;
    private javax.swing.JTextField TxtDestinoVuelo;
    private javax.swing.JTextField TxtDireccionCliente;
    private javax.swing.JTextField TxtHoraLlegadaVuelo;
    private javax.swing.JTextField TxtHoraSalidaVuelo;
    private javax.swing.JTextPane TxtNitAerolinea;
    private javax.swing.JTextPane TxtNombreAerolinea;
    private javax.swing.JTextField TxtNombreAgente;
    private javax.swing.JTextField TxtNombreCliente;
    private javax.swing.JTextField TxtOrigenVuelo;
    private javax.swing.JTextField TxtPasaporteCliente;
    private javax.swing.JTextField TxtTelefonoAgente;
    private javax.swing.JTextField TxtTelefonoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
}
